### ISSUE TITLE
Hyperlinks in ODI content taxonomy widget

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#152]
Some hyperlinks to topic pages are not currently working, e.g. "Aid and development" and "Urban administration and development". This may be due to recent updating of categories on Open Development Mekong.

![image](https://cloud.githubusercontent.com/assets/1206387/8182288/37d71786-1458-11e5-89bd-795f0ac95339.png)

**Comment by acorbi** [comment]
@Huyeng Can you please take a look at this?

**Comment by Huyeng** [comment]
The Hyperlinks of the topic area don't work  because the name of the taxonomy and the page slug of the topic doesn't associate with each other. 

Recalled this issue: https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/61

Maybe, I can associate the taxonomy name with the page title instead.

**Comment by Huyeng** [comment]
Decided solution: update the code to associate the taxonomy name with the page title.

**Comment by Huyeng** [comment]
Code updated. However the Industries  still not has hyperlink. @DBishton, please check to make sure the Industries of topic page exists, or the taxonomy/category name is exactly the same topic title.

**Comment by Huyeng** [comment]
Fixed.

**Comment by Huyeng** [comment]
Pulled the code change and fixed it now.
