### ISSUE TITLE
Investigate RSS Multi importer configuration/CRON schedule

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#168]
@Huyeng The RSS multi importer plugin has stopped updating its feed database as of June 17, 2015. It is no longer importing feed items or creating auto posts. Manually updating the feeds database caused all draft autoposts from this year to be deleted.

**Comment by DBishton** [comment]
This is quite urgent as we need to publish news daily now. Thank you.

**Comment by acorbi** [comment]
@DBishton @Huyeng I'll tell dear, could be that the cron tasks have not been moved to the new server...

**Comment by Huyeng** [comment]
Since the beginning, the RSS importer implemented without configuring the cron job on the server!
Currently, it is working well.

**Comment by acorbi** [comment]
@Huyeng I would suggest to check the logs of both the plugin and the cron daemon. Have you done it?

**Comment by Huyeng** [comment]
I don't see the log of that plugin. I will check it again. 
The issue, it is under investigate. I noticed that there are some news feeds imported to its list/db, but it won't import/migrate to the Autopost.  
See this: 
![screenshot_12](https://cloud.githubusercontent.com/assets/6613530/8564835/0046cde2-257a-11e5-8890-ffe7349d7253.jpg)

The plugin is using the wordpress cron job instead of the Linux cron job as default. The cron job task on the server will be implemented for some case.

**Comment by DBishton** [comment]
Thank you @Huyeng, this seems to be working correctly now. This has been an intermittent issue in the past, so I will re-open if it occurs again.
