### ISSUE TITLE
Map Explorer Myanmar fails to load

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#228]
Map Explorer for Myanmar is currently not loading completely, making it non functional.

https://myanmar.opendevelopmentmekong.net/map-explorer/

Display is "duplicated" also, see below:

![image](https://cloud.githubusercontent.com/assets/1206387/8671164/0d461e08-2a4d-11e5-9cf3-0402967cfeb1.png)

Currently the map contains only a single layer:
https://myanmar.opendevelopmentmekong.net/wp-admin/post.php?post=75&action=edit&message=1

Calling a CartoDB visualisation: https://odm.cartodb.com/api/v2/viz/696f540e-29a5-11e5-8eee-0e018d66dc29/viz.json

**Comment by DBishton** [comment]
Note, this started happening for the Laos map explorer when I added this layer: https://laos.opendevelopmentmekong.net/wp-admin/post.php?post=167&action=edit

I have changed the status of this layer to draft until this is resolved.

**Comment by acorbi** [comment]
@DBishton @Huyeng @Numnov Please note that both myanmar and laos map explorer pages were showing the map explorer twice. 
![bildschirmfoto 2015-07-14 um 19 04 35](https://cloud.githubusercontent.com/assets/384894/8679596/cab8943a-2a5b-11e5-920c-67cd2b69b3c3.png)
![bildschirmfoto 2015-07-14 um 19 06 58](https://cloud.githubusercontent.com/assets/384894/8679597/cabe44ac-2a5b-11e5-996c-ee9fd71657c2.png)

This is due to an error of configuration on the wordpress page. To configure it properly, following things should be considered:
1. Map explorer pages need to get assigned the **Map explorer** page template:
   ![bildschirmfoto 2015-07-14 um 19 05 17](https://cloud.githubusercontent.com/assets/384894/8679620/f26c0e58-2a5b-11e5-8679-a4592b0911b6.png)
2. This template does include the map explorer per default, so there is no need to add the shortcode **[odmap]** in its content as it was the case:
   ![bildschirmfoto 2015-07-14 um 19 05 22](https://cloud.githubusercontent.com/assets/384894/8679633/14f0f330-2a5c-11e5-8b61-16cd85514af2.png)

I have fixed it on both sites and also in the thailand and cambodia one, which were presenting the same Issue
