### ISSUE TITLE
"Related news" widget does not display for "Environment and natural resources" category

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#229]
The "Related news" widget is currently not appearing on the topic page for "Environment and Natural Resources". 

There are news items tagged under this topic that should be displayed here.

![image](https://cloud.githubusercontent.com/assets/1206387/8673945/e0af9118-2a64-11e5-851c-0b93b11ed4a8.png)

**Comment by acorbi** [comment]
@DBishton  The reason for this is that the widget is pulling the news from the category "Environmental and natural resources" which should have the corresponding slug: environmental-and-natural-resources.

I have gone through the list of post categories on wordpress and notices that:
1. There is a category "Environmental and natural resources" with 13 posts assigend but has "environment" as slug
   ![bildschirmfoto 2015-07-14 um 19 26 19](https://cloud.githubusercontent.com/assets/384894/8679966/78c36a1c-2a5e-11e5-848e-c2b9d0894886.png)
2. There is a category "Environmental and natural resources" with the proper slug "environmental-and-natural-resources" but with 0  posts.

So, in order to fix this Issue, either change the slug in the category which has 13 posts assigned or add those posts to the category which has the proper slug.

**Comment by DBishton** [comment]
Thanks @acorbi!
