### ISSUE TITLE
Briefing summaries too long in Khmer

### ISSUE THREAD

**Issue by mishari** [OpenDevelopmentMekong/opendev-wptheme#27]
<a href="https://github.com/DBishton"><img src="https://avatars.githubusercontent.com/u/1206387?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [DBishton](https://github.com/DBishton)**
_Thursday Mar 05, 2015 at 14:43 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/oeco/opendev-wptheme/issues/46_

---

Please reduce character limit to be in line with the English summaries.

Khmer:
![image](https://cloud.githubusercontent.com/assets/1206387/6506805/3f7f590e-c380-11e4-8b82-dff91fba8fa2.png)

English:
![image](https://cloud.githubusercontent.com/assets/1206387/6506811/4a46bf94-c380-11e4-9e24-648ce586afde.png)

**Comment by mishari** [comment]
The source of this problem can be found in [the manual](http://codex.wordpress.org/Function_Reference/the_excerpt):

> "An auto-generated excerpt will also have all shortcodes and tags removed. It is trimmed down to a word-boundary and the default length is 55 words. For languages in which words are (or can be) described with single characters (ie. East-Asian languages) the word-boundary is actually the character."

Since there are 55 spaces, it thinks there are 55 (really long) words being given out in the excerpt. It is unclear what an appropriate fix for this will be.

**Comment by Huyeng** [comment]
Suggest to add the summary into excerpt box where under the content box, so the problem is fixed.  Please add the summary texts of the languages into excerpt box by clicking on flag icon to switch languages. 

Look at the screenshots as an example:
![excerpt-box](https://cloud.githubusercontent.com/assets/6613530/6684021/900bab32-ccbf-11e4-848b-69f2acc829e6.jpg)

![excerpt-box-en](https://cloud.githubusercontent.com/assets/6613530/6684059/fa024762-ccbf-11e4-8ec9-486347523ffc.jpg)

**Comment by mishari** [comment]
@Huyeng this is a good solution.
