### ISSUE TITLE
Bring back responsive behaviour - Top LOGO Still Not Aligned Correctly

### ISSUE THREAD

**Issue by chris-aeviator** [OpenDevelopmentMekong/opendev-wptheme#346]
Before nav implementation there was responsive behaviour  provided by jeo/jeo-odm theme.
Bring back responsive layout based on the old media queries.

Also elaborate the use of display:flex functionality.

**Comment by acorbi** [comment]
Related issue https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/344

**Comment by kathi-aeviator** [comment]
@acorbi can you close that issue if not necessary?

**Comment by chris-aeviator** [comment]
https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/344

**Comment by jpeizer1** [comment]
LOGO Still not correctly aligned so that text is LEFT ALIGNED TO THE LOGO  on the top of screen on wide screens. This is an IMPORTANT standards and branding issue as I have indicated numerous times over the last week.

![logo-problem](https://cloud.githubusercontent.com/assets/16559612/12426627/a2ab3f88-bea8-11e5-9809-96669206c575.JPG)

**Comment by Huyeng** [comment]
This issue is fixed together with the issue #587.
