### ISSUE TITLE
Embedded elements not responsive in the Briefing pages

### ISSUE THREAD

**Issue by Numnov** [OpenDevelopmentMekong/opendev-wptheme#37]
@mishari , many of the embedded elements in briefing pages (image assets stored in WordPress, embedded Tableau Public visualisations, embedded JEO maps) do not scale correctly:

![embedding issue](https://cloud.githubusercontent.com/assets/4859982/6891500/ee3cf208-d6e5-11e4-9fd2-d3cbee844cc6.png)

Is it possible to fix this?

Example URLs: http://opendevelopmentmekong.net/briefings/hydropower/
http://opendevelopmentmekong.net/briefings/forests-and-forestry/

**Comment by mishari** [comment]
The temporary fix is that when the editors add a map, to change the width from an absolute to a percentage, as illustrated:
![edit_briefing_ _open_development_mekong_ _wordpress](https://cloud.githubusercontent.com/assets/503018/6917712/569e2de4-d7d1-11e4-8b9d-12990d6d27d1.png)
![edit_briefing_ _open_development_mekong_ _wordpress](https://cloud.githubusercontent.com/assets/503018/6917727/838116aa-d7d1-11e4-9951-3ce75917e5cb.png)

**Comment by mishari** [comment]
@Huyeng do you know anything about this?

**Comment by acorbi** [comment]
I have been testing this and could determine:
- **Images** scale correctly
- **Feature boxes** scale correctly
- **Tableau visualizations** scale correctly but content gets chopped thus loosing information.
  ![bildschirmfoto 2015-05-03 um 17 08 32](https://cloud.githubusercontent.com/assets/384894/7445506/78000052-f1b7-11e4-9af2-1cd021a7e951.png)
- **Map** scales correctly. I checked the code and width="100%" was specified in the code as mentioned by @mishari 

Can we then close this Issue and tell editors to do this change manually? or should a method be implemented so maps get automatically imported with that parameter set in order to make editor's task easier? In the second case, a new Issue should be opened, analysed and estimated.

**Comment by DBishton** [comment]
Hi folks, we will be developing a set of instructions and style guidelines on how standardise Tableau visualisations (and embedding), so we will include the instructions above in those.
