### ISSUE TITLE
Find shorter discription-name

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/opendev-wptheme#378]
Is there a possibility to shorten the discription words of "document number" and "promulgation date" this will be a problem especially for responsive devices.

**Comment by kathi-aeviator** [comment]
@DBishton please feedback this issue.

**Comment by acorbi** [comment]
@kathi-aeviator I do not think the solution should involve shortening the header texts, what about the Law's titles??? they are 3x longer.... 

In my opinion, this should be addressed from the design perspective ( i.e using icons on layout or small screens ). Since there is no proposal for those yet, I would close this issue.

**Comment by kathi-aeviator** [comment]
@acorbi working on it...

**Comment by kathi-aeviator** [comment]
From my side it needs to be shorter. Just "number" and "date" is specifically enought.

**Comment by acorbi** [comment]
@kathi-aeviator I do not think that is a good idea, for a law knowing that it is the promulgation date and not the date it was uploaded to the system is important. @gimmemochi can provide more context than me though. @gimmemochi can you shed some light on the final name for the metadata fields on https://pp.opendevelopmentmekong.net/laws/ ?

**Comment by kathi-aeviator** [comment]
so let's do it like this and see later how we fix the problem in mobile. Closed issue.
