### ISSUE TITLE
Whitelist solution for image tags in RSS Multi Importer auto-posts

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#41]
Currently we have excluded HTML from auto-posts crated by the RSS Multi Importer as it causes a major formatting issue. We want to include images in these posts if they exist in the feed items.

Can we implement a whitelist solution for image HTML tags to allow these through?

**Comment by mishari** [comment]
The issue lies in here somewhere:
https://github.com/OpenDevelopmentMekong/odm-frontend/blob/master/wp-content/plugins/wp-rss-multi-importer/inc/excerpt_functions.php#L244-L247

By default the plugin strips all tags already except for `<a><img><p><br>` which seems pretty reasonable. I want to know under which circumstances does this break functionality as this issue could be a CSS issue rather than a strip tag issue.

**Comment by mishari** [comment]
The fix is to use another truncate function from cakephp that can preserve tags. https://github.com/cakephp/cakephp/blob/113ebb19bcd45933823fa775ffbc08f374d97807/src/Utility/Text.php#L445-L602

**Comment by mishari** [comment]
@DBishton @Huyeng ok I've been thinking about this some more.. I have some ideas on how to fix this and the problem in https://github.com/oeco/opendev-wptheme/issues/10 but let's unset the strip html tags and we'll fix the issues as they appear.
