### ISSUE TITLE
"Add border" feature for text on topic pages

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#441]
We currently use a plugin called "WP Feature box" (https://wordpress.org/plugins/wp-feature-box/) to mark out special areas of text on topic pages. It's not very good for this -- size can't be adjusted, text can't be styled.

![featurebox](https://cloud.githubusercontent.com/assets/1206387/12346796/493b7baa-bb8a-11e5-8ae3-31c523f0676b.png)

What we needed is a feature, ideally integrated into the Wordpress text editor, that allows editors to choose a paragraph of text and add a nice-looking, simple border to it.

**Comment by kathi-aeviator** [comment]
The easiest way to deal with would be to make a temporary solution for this issue. Otherwise it would be a huge new construction site - better to drop into part 2 of milestone 7... But totally understand your needs! 

Questions:

-> are there any possibilities to adapt the content to the general look and feels with the plugin?
-> we would like to postpoem a custom-plugin for Part 2

**Comment by Huyeng** [comment]
I have updated the plugin to enable the rich text, so you can format the content as you wish.  Moreover, if you would like add the border like the screenshot, you can do that by adding the block-quote attribute in the topic page. 
![screenshot_13](https://cloud.githubusercontent.com/assets/6613530/12971640/f082670c-d0cf-11e5-9a26-d15b00eb6403.jpg)

![screenshot_8](https://cloud.githubusercontent.com/assets/6613530/12971606/89f333c2-d0cf-11e5-9578-5c9e98897ed9.jpg)
