### ISSUE TITLE
Map Explorer: Make map full height

### ISSUE THREAD

**Issue by chris-aeviator** [OpenDevelopmentMekong/opendev-wptheme#447]
On HUGE screen sizes the map is not set to occupy full height of the screen.

![Map explorer height](https://cloud.githubusercontent.com/assets/16559612/12336765/268896a8-bad4-11e5-97ee-6d20dc23fe9d.JPG)
Screenshot taken from https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/433

**Comment by chris-aeviator** [comment]
@jpeizer1 
Updated map explorer on PP,
please test the map on 24" screen if it now occupies all of your screen size and does not leave any white space like in the screenshot above!

**Comment by jpeizer1** [comment]
It looks good wide screen - The logo is still not aligned to the left which I would expect is a pretty trivial fix in the larger scope of things and is a continuing source of political frustration for me because the powers-that-be look at that simple fix to the logo which still doesn't fully look right on  the big screen as a reflection of other elements of the work -- But i have conveyed that a number of times already to you and we'll have to deal with the results of that issue later...

![map-bigscreen](https://cloud.githubusercontent.com/assets/16559612/12372189/fcf3163e-bc1c-11e5-9660-cd4e3c3a6c8e.JPG)

**Comment by chris-aeviator** [comment]
@jpeizer1 

Thanks for confirming!
Please see the topic of this issue. The issue only deals with the **height of the map container**, nothing else. We cannot start to mix up work, as I explained in the corresponding issue it was new functionality causing that issue, and we will deal with it in the right place on the right time. Now mapper staff is waiting for map explorer to be finished. As already mentioned we will deal with responsive issues in the next step.

**Comment by acorbi** [comment]
@jpeizer1 @chris-aeviator @DBishton I second @chris-aeviator point. Map explorer should go out first. UI finetunning is a quick thing and should be approached once major issues/features are complete

**Comment by jpeizer1** [comment]
@corbi @chris-aeviator @DBishton I can actually deal with that operational set of priorities because its a necessity and as long as its clearly communicated to me, and in fact it happens like that its fine  -- But when I have to tell the people I report to that this will be done on X date because that's what I have been told and then communication is not forthcoming and they see this stuff it puts me in a rather awkward position... Because then I have to further convince them that YES is will be taken care of -- while they are telling me appropriately -- "well you told us that other thing would be taken care of by now too!" So transparent and continued communications in this case is _KEY_.
