### ISSUE TITLE
RELATED RESOURCES: labels should be in Khmer 

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/opendev-wptheme#450]
1. RELATED RESOURCES should appear in Khmer on the Khmer page.
2. Label (title) of resources linked from CKAN to WP should in Khmer. 
   ![screen shot 2016-01-15 at 5 03 02 pm](https://cloud.githubusercontent.com/assets/6489398/12350806/e1f4c5f6-bbab-11e5-84cb-6c8c765601a6.png)

**Comment by acorbi** [comment]
Suggestions for fixing this:
1. The string "Related resources" should be added to the localization workflow (if not done yet) and files with translated files (.po) should be deployed so that string appears translated when the user changes languages.
2. Code for those widgets should be adapted so wpckan returns the field "title_translated" (along with other metadata) and the string presented should be the corresponding one to the current language **lang**. title_translated[lang]
