### ISSUE TITLE
Laws on Wp have scrollbar

### ISSUE THREAD

**Issue by kathi-aeviator** [OpenDevelopmentMekong/opendev-wptheme#523]
@alex 
why do you used scrollbar function for laws section here?

![image](https://cloud.githubusercontent.com/assets/15011163/12387699/c07add0a-bdce-11e5-823f-9aebe66f0155.png)

**Comment by kathi-aeviator** [comment]
Thats totally not functional and its need to be changed before launch.

**Comment by acorbi** [comment]
agree, unfortunately I cannot undertake any more tasks :disappointed: . @Huyeng you have a lot of experience with datatables and are the most appropiate person to approach this, im assigning this task to you.

**Comment by chris-aeviator** [comment]
why has this been changed? in my implementation it was not there?!

**Comment by chris-aeviator** [comment]
@Huyeng feel free to contact me for advise, we can lookup in commit history!

**Comment by acorbi** [comment]
@chris-aeviator your implementation was in baby steps when i overtook it and needed to be completely refactored because it had, in my opinion, an incorrect approach ( several dataTables instances instead of one).

**Comment by chris-aeviator** [comment]
only thing is please communicate before going that dramatic step!

The approach is valid as these steps are supported by the data_table api

**Comment by acorbi** [comment]
@chris-aeviator @kathi-aeviator it had been already communicated -> see https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/415 and discussed!

You approach of maintaining multiple datatable instances involved writing a genenal pagination, index and info logic for ALL tables when this functionality is shipped out of the box by datatables instead of implementing **grouping** which for me makes more sense: http://datatables.net/examples/advanced_init/row_grouping.html

**Comment by acorbi** [comment]
@chris-aeviator @kathi-aeviator it had been already communicated -> see https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/415 and discussed!

You approach of maintaining multiple datatable instances involved writing a genenal pagination, index and info logic for ALL tables when this functionality is shipped out of the box by datatables instead of implementing **grouping** which for me makes more sense: http://datatables.net/examples/advanced_init/row_grouping.html

**Comment by chris-aeviator** [comment]
@acorbi 
another valid approach it solving the document type display with "title rows" & colspan, see implementation of the old laws section on odc website
![bildschirmfoto 2016-01-18 um 19 58 17](https://cloud.githubusercontent.com/assets/11522213/12391935/de706bdc-be1d-11e5-8795-296d5375c5f5.png)

**Comment by Huyeng** [comment]
The scrollbar of laws section are removed. Page will fully view.
