### ISSUE TITLE
"Urban administration and development" menu items cut off

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#572]
Please display full title. If not possible in timeframe, remove "and" from menu item.

**Comment by chris-aeviator** [comment]
fixed with https://github.com/OpenDevelopmentMekong/opendev-wptheme/commit/4773b44f4ab822266bcb9d8fe83c55e0df8df3e1 and implemented on http://pp.opendevelopmentmekong.net

**Comment by jpeizer1** [comment]
Chris, on January 20th after two weeks of asking for the logo to be fixed and being told by Aeviator "We'll get to it, We'll get to it"  -- We went into a presentation with a roomful of donors with the logo STILL UNFIXED --- and the text overlapping ICONS on the next line -DURING THE PRESENTATION- making our work look amateurish and the local Cambodian presenter totally losing face in front of a room full of donors. 

So let's be clear -- This item _IS NOT FIXED_ and should not be closed before the same _BUG_ is fixed by Aeviator on ALL the country menu's as well as MEKONG because you are responsible for it. 

If the system still has open bugs EWMI will not sign off on acceptance. And if EWMI doesn't sign off on acceptance no further payment will be forthcoming. I've been mandated as the person to decide when acceptance is appropriate.

I hope all is clear now. Partial fixes will not be deemed acceptable and I do not regard this _bug_ as fixed when it still exists on five other menus -- just so you clearly understand what my standards are. You will be dealing with Dan and Huy Eng on a daily basis. I will be looking at the final product.   -JP-

**Comment by chris-aeviator** [comment]
JP I cannot see what you are referring to. This issue is about one multi line menu item ( urban administration and development ) please check this on PP Wordpress and close again or refer to the detail that's missing. This has clearly nothing to do with the logo. We are coordinating with Dan continuously, please contact him for setting priorities.

**Comment by jpeizer1** [comment]
@chris-aeviator  We need consistency related to Github Issue closures in Production versus PP- and I have emailed @DBishton to coordinate. Post-Deployment Huy Eng and Alex are closing issues after they have been moved into production. Apparently Aeviator is closing issues like this one that are still only resolved in PP-   

So we need all the developers doing the same thing to determine what is legitimately a closed issue. Prior to deployment there was a process that moved all PP- closed issues altogether into production at the time of deployment. Currently issues being resolved by Huy Eng and Alex are individually moved to production and then closed - where the fix is viewed by testers.

**Comment by Huyeng** [comment]
The texts "Urban administration and development" on the menu items cut off was fixed, but the code was not pulled to the Production. I pulled it now, so it fixed.

![screenshot_10](https://cloud.githubusercontent.com/assets/6613530/12713596/24a89856-c902-11e5-9db6-fa95c1514a9f.jpg)
