### ISSUE TITLE
Map Explorer/Interactive map not displaying layers correctly

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#59]
"Map Explorer" (http://opendevelopmentmekong.net/map-explorer/) does not display layers correctly. Activating the CartoDB-hosted layer should display the data, it does not. 

![image](https://cloud.githubusercontent.com/assets/1206387/7368584/a96832c8-edd3-11e4-8653-f33fc4cdf8d4.png)

This layer displays correctly elsewhere on the site:http://opendevelopmentmekong.net/maps/greater-mekong-subregion-hydropower-dams-2014/#!/map=54158 -- click "Known Hydropower" tab to view.

![image](https://cloud.githubusercontent.com/assets/1206387/7368604/07f14cd0-edd4-11e4-9511-e7f21a3de070.png)

**Comment by acorbi** [comment]
@Huyeng  Looking at the browser console, I could see following error that might be the cause of the Issue:

![bildschirmfoto 2015-05-03 um 16 29 18](https://cloud.githubusercontent.com/assets/384894/7445408/b44e03a2-f1b1-11e4-8e41-30da770f4c6c.png)

**Comment by Huyeng** [comment]
Based on my investigation, the functionality of the map explorer, it will load all the published may layers. And I noticed that some map layers published are not working properly.  Thus, the Map explorer doesn't work caused by adding the wrong formats URLs of the other map layers such as Blue Marble Standard Layer for Testing, Forest Cover Gain Loss CartoDB, Forest cover Greater Mekong Subregion 2014 and GMS Forest cover 2000. For now, I just marked theme as Pending Review, please check and correct the map urls before publishing. Now the Map explorer is working fine. Please have a look.
