### ISSUE TITLE
OD Content Taxonomy widget to allow navigation

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#61]
The OD Content Taxonomy widget must contain links to briefings, if they exist. This will be the only way for users to navigate through the topic areas once on a briefing page. Briefings will have the same names and slugs as the category titles.

![image](https://cloud.githubusercontent.com/assets/1206387/7369400/fd2cff08-eddb-11e4-8d86-32ad8394f261.png)

**Comment by acorbi** [comment]
I believe we should distinguish between **taxonomic terms** ( implemented throught the categories in wp) and **briefings**. We should find the way to be able to associate a Briefing to a taxonomic term (with the same name?) in order to be able to obtain the link to the Briefing page.

@DBishton / @Huyeng : Are briefing pages getting just and only 1 taxonomic term, or what it is the same, one wp category?

**Comment by Huyeng** [comment]
@Alex, a briefing/topic page could category in different taxonomies and the briefing/topic pages will also category to the same category. 

@DBishton, in order to change navigate of Taxonomy terms in OD Content Taxonomy widget to the briefing/topic pages, we have to associate the Briefing/Topic to a taxonomic term like Alex Said. 
So, I would like to suggest that, using the Slugs of Briefing /Topic to associate with the Taxonomic Term Names. Thus the Editors should to keep in mind that the Slugs of Briefing /Topic must be exactly the same as Taxonomic Term Names. 
For example, if Taxonomy Term Name "Environmental change and protection", so the slug of the page should be "environmental-change-and-protection" (convert to lowercase and replace space with dash).

![screenshot_7](https://cloud.githubusercontent.com/assets/6613530/7449081/138ee3b8-f257-11e4-9948-2d4c50ec5ee9.jpg) 

**Well, you don't need to lowercase and replace space with the dash, just copy the title into the Permalink under the Title box, it will automatically generate itself. See the screen below.**

![screenshot_8](https://cloud.githubusercontent.com/assets/6613530/7449095/7d37b538-f257-11e4-94f3-3bbafb34697d.jpg)
- After click OK
  ![screenshot_6](https://cloud.githubusercontent.com/assets/6613530/7449096/7fe309fe-f257-11e4-9a0f-a9869079ac7d.jpg)

*_Note that, there is no number add the end of the slug eg. "environment-and-natural-resources-2". If the slug and term are not exactly the same, the link won't show up. *_

**Comment by acorbi** [comment]
@Huyeng @DBishton The solution proposed by Huy Eng is definitelly valid and would not involve high implementation costs. 

It only has a problem tho: that it is error prone. Editors should be very aware of this instructions and how to name the Topic pages properly. If that is guaranteed, then it will work.

**Comment by DBishton** [comment]
@Huyeng and @acorbi Thank you for your thoughts and proposed solution on this. A 1:1 relationship between pages and taxonomic categories is necessary for this solution, correct? This is my assumption,  but we should discuss if there are other options that are preferable (such as the category association suggested above).

**Comment by acorbi** [comment]
@Huyeng @DBishton Sorry guys, I am still not sure which one is the preferred. Let's have a quick discussion about this somewhen soon.

**Comment by DBishton** [comment]
@acorbi I think @Huyeng's proposed solution is a good one. At this stage, there is no need for a one-to-many relationship between categories and topic pages. The only posts that would have more than one applied would be news summaries. I would suggest we go with that solution as it has the lowest implementation cost to solve the problem -- we can revisit the issue in future if requirements change.

**Comment by acorbi** [comment]
OK, let's go ahead with @Huyeng's proposal.

**Comment by Huyeng** [comment]
Implemented and uploaded to the live server. Please have a look and let me know if you have any comment. 
Do you think that the children should be initially collapsed, and will expand once clicked on the expand icon or sth?

**Comment by acorbi** [comment]
@Huyeng I like the way it is implemented! :+1: 
Regarding the children, I would only expand the children of the current selected topic so they user knows where they currently are. Just like it is implemented now, I would close the  Issue, looks good for me.

**Comment by Huyeng** [comment]
I would like to close the issue.  if there is something need to change, let create new issue.
