### ISSUE TITLE
Contact form button disturbs scrolling

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#618]
Currently, the yellow contact form button is placed over the scroll bar which makes it difficult to scroll vertically on the site. It should be placed on another place. My suggestion would be to integrate it on the left sidebar at the bottom of it.

![screenshot from 2016-01-24 11-12-55](https://cloud.githubusercontent.com/assets/384894/12535692/b130ea12-c28b-11e5-9a35-102377b10cf3.png)

**Comment by Huyeng** [comment]
Where do you think the button should place on the site? Below are the screenshot that you can choose or share your comment if you have. 
![screenshot_12](https://cloud.githubusercontent.com/assets/6613530/12804970/7821f426-cb2a-11e5-974a-b0d8930be8dd.jpg)
![screenshot_11](https://cloud.githubusercontent.com/assets/6613530/12804976/7cdded80-cb2a-11e5-8840-84f962890928.jpg)
![screenshot_10](https://cloud.githubusercontent.com/assets/6613530/12804977/7f53d840-cb2a-11e5-9cba-d29ae3fadf3b.jpg)
![screenshot_9](https://cloud.githubusercontent.com/assets/6613530/12804980/81272262-cb2a-11e5-834f-978761710785.jpg)

**Comment by jpeizer1** [comment]
@Huyeng I think the Contact form is a large nuisance where it is now ;-) - It seesm to get in teh way of everything - I think it would be much better where you actually suggested it #3 on the left sidebar at the bottom.

**Comment by Huyeng** [comment]
Moved to the left bottom.

**Comment by jpeizer1** [comment]
@Huyeng Can you please check the CONTACT FORM button -- when you mouseover it, the button "moves" a few pixels (alignment is off). Also Can we move the bottom up "just a little" so its not so close to Windows START button on browser -- maybe just making contact button a little thinner would work.

Otherwise I like it very much over there! And we're all thankful the two lines are gone.

**Comment by Huyeng** [comment]
That's the styling effect on mouseover. If you don't like, i can disable it.

**Comment by jpeizer1** [comment]
@Huyeng  Could you look carefully at this? -- what is happening is that the orange background is actually moving down about two pixels on mouseover making the box look bigger and breaking the thin white background around the orange background - it looks like the alignment is different between mouseover and nonmouseover rather than a standard mouseover effect. If it really is a mouseover effect could we disable that and simply have the text change color instead on mouseover? I'd also move it up so that the bottom edge of button was where CONTACT FORM text is now so that its a bit more separated from Windows menu items at bottom and people  don't accidentally click that or overlook the button because its so close.

**Comment by Huyeng** [comment]
It is the mouseover effect. Anyways, it was fixed as your suggestion.
