### ISSUE TITLE
Add Baselayer into the Map explorer 

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/opendev-wptheme#717]
Addition of base layer options directly selectable on the Map Explorer to include: [tbc]
o    Primary clean shade relief map – upon loading
o    Satellite image
o    Landsat
o    Topo Map
o    EnviSat

**Comment by prustar** [comment]
After discussions with Try today this seems to be a function that users have enjoyed because it had allowed them to view the concessions overlaid upon a satellite image and when hovered over a polygon with the mouse it became transparent. People liked the ability to have the option to change the base layers for their analysis. Could we please reinstate this function. See screen shots below of the function: 

![elc](https://cloud.githubusercontent.com/assets/14996905/15611022/a603d2f4-2428-11e6-9db8-258c3a366f99.JPG)
![elc2](https://cloud.githubusercontent.com/assets/14996905/15611023/a6089410-2428-11e6-8640-9427aa1612bb.JPG)

**Comment by acorbi** [comment]
Closing this Issue, it is already implemented
