### ISSUE TITLE
Add documentation about Cambodia folder on README.md

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#811]
Hi @Huyeng,

I have noticed that on https://github.com/OpenDevelopmentMekong/opendev-wptheme/tree/master/Cambodia you have uploaded a series of php files with some templates.  I understand this is code from the legacy site that will be eventually reused but I am not sure if it is actually linked from somewhere within the site.

Can you maybe add some documentation on the README.md file for clarity? Thanks

**Comment by acorbi** [comment]
@Huyeng please provide feedback on this one

**Comment by Huyeng** [comment]
Well, those are the templates that were created for the Forest Cover pages on the new site. it won't use for the other country sites. 

The ideas to create the Cambodia directory in the child theme are that just would like to separate the specific files/templates of the country from the universal templates because each country has different projects/pages likes Cambodia's forest cover, https://cambodia.opendevelopmentmekong.net/en/issues/forest-cover/

Moreover, I would like to filter the templates which belong to the country to list on Template dialogue for that country only. Thus, if those template won't related to the other countries, they won't list on the Template metabox. However, this is just the idea, has not implemented yet.
