### ISSUE TITLE
MAP- EXPLORER - ELC Layer - Big Bug - Clicking Table Icon Produces Program Error

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#838]
Selecting the ELC Table using map Explorer table Icon on ELC layer now produces a program error  instead of pulling up the ELC Table Page

![elc-table-error](https://cloud.githubusercontent.com/assets/16559612/14990847/9e32d822-112c-11e6-965e-465c17ddce5c.JPG)

I clicked this table icon to get this result and I assume the configuration format with the Table Icon (#837) is related to this problem.
![elc-table](https://cloud.githubusercontent.com/assets/16559612/14990860/ac16b5f8-112c-11e6-8634-c0f55497550e.JPG)

**Comment by acorbi** [comment]
@jpeizer1 @Huyeng This issue happens because that table icon is linking to the previous ELC implementation under https://cambodia.opendevelopmentmekong.net/company-profiles/economic-land-concessions/ . The new one is on https://cambodia.opendevelopmentmekong.net/profiles/economic-land-concessions/ 

I am not sure if I have time to fix this today. @Huyeng please give it a look if you see this Issue is not closed by tomorrow

**Comment by jpeizer1** [comment]
Clicking the Table Icon link now resolves to a 404 error page rather than aborting outright

![elc-table-error](https://cloud.githubusercontent.com/assets/16559612/14998971/70bad57a-1154-11e6-9105-f6b7abae510d.JPG)

**Comment by Huyeng** [comment]
The links on the menu and icon are still pointed to the old page. I just updated them. Fixed!
