### ISSUE TITLE
Testing Profile pages in PP tables not visible

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/opendev-wptheme#859]
The profile pages have the correct CKAN entry listed and the link works however it is not displaying the table on the front end: 
![image](https://cloud.githubusercontent.com/assets/14996905/15185701/9d2807ee-179a-11e6-8321-82eef1dc5528.png)

CKAN CSV resource working see link: https://data.opendevelopmentmekong.net/dataset/protected-areas/resource/1dd25581-01bc-4ed6-a7cb-ea10c7192f8f?type=dataset

@Huyeng @punwath @DBishton - Before I speak with Try regarding the upload of these pages and potentially decommissioning the site it would be good to show him something that works. If we can get these 4 uploaded and working at least on the pp site then it would help.

**Comment by Huyeng** [comment]
The issue caused by CKAN. The information of profile is loaded from CKAN API. However, it seems to have a problem with Datastore of CKAN that caused errors. 
@Punwath has uploaded the CSV of protected area to CKAN which link below:
https://data.opendevelopmentmekong.net/dataset/protected-areas/resource/1dd25581-01bc-4ed6-a7cb-ea10c7192f8f?type=dataset
However, getting resource from CKAN API results no found. 
https://data.opendevelopmentmekong.net/api/3/action/datastore_search?resource_id=1dd25581-01bc-4ed6-a7cb-ea10c7192f8f&limit=1000

@acorbi will check for this issue soon.

**Comment by acorbi** [comment]
@prustar @Huyeng you are right. Yesterday I discovered that datapusher was down and therefore those CSV files were not pushed to the datastore and therefore no results were found through the api. I coordinated with Proteus and now is fixed. Resources for other proifiles need to be pushed manually to the datastore in order to be exposed over the API. Steps:
1. Go to the resource
2. Click on manage
3. Click the datastore tab
4. Click the upload to datastore button
