### ISSUE TITLE
OD Mekong map explorer loading never completes

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#918]
When loading the map explorer on OD Mekong, the screen doesn't load completely, and a white box is visible on the screen -- see screenshot below.

![image](https://cloud.githubusercontent.com/assets/1206387/16030674/c6eba552-321d-11e6-883c-bd418e03183b.png)

Layers will render, but the white box remain and the browser still indicates that the page hasn't completed loading.

![image](https://cloud.githubusercontent.com/assets/1206387/16030688/f29c864e-321d-11e6-9565-2d4d8e353951.png)

**Comment by Huyeng** [comment]
It's loading fine to me.  

![screenshot_5](https://cloud.githubusercontent.com/assets/6613530/16031255/53b96e4c-3223-11e6-8b73-346c2dee9c8f.png)

**Comment by acorbi** [comment]
yeah, that looks like a small glitch that caused that particular tile not to load. probably refreshing with CTRL + F5 or moving the map or changing the zoom level so other tiles are loaded should fix. im closing this issue, thanks for reporting @DBishton !

**Comment by jpeizer1** [comment]
@acorbi @DBishton @prustar If a number of us are WHO KNOW THE SYSTEM  are having these issues which are resolved by CTRL+F5 - but we report them not realizing they can be resolved by CTRL+F5 then you can bet a lot of users are having these same issues -- and their resolution may simply be not to use the system because they assume it doesn't work. And if it resolves itself for a user on one day, and then the next they have the problem or a different problem with the same resolution - then for them the perception is that system is unstable. If these issues are going to continually pop up then WE MUST have some indication that you can use CTRL+F5 (or whatever method) to resolve these issues so that users just don't give up and go away.... We can't just assume everyone is technically savvy enough to know what to do, particularly if we are reporting errors ourselves.
