### ISSUE TITLE
"Related news" widget not appearing

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#933]
The related news widget is not displaying on the "Land" landing page draft: https://opendevelopmentmekong.net/?post_type=topic&p=177464&preview=true

Settings option is set to "Related to the topics".

@Huyeng, what are the criteria for displaying news? Shouldn't the most recent articles with any "land" tag appear here?

**Comment by Huyeng** [comment]
@DBishton, the related news will show if the page is viewed with the real url like this: https://opendevelopmentmekong.net/topics/land
The reason is that, the news will be queried from the specific category based on the page slug "land". 
Thus, if the page is preview, the related new won't appear. if you view the real url, it will be there.

**Comment by DBishton** [comment]
@Huyeng Fantastic, thank you for the explanation.
