### ISSUE TITLE
Re-arrange the order of the layers per drag-and-drop

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#95]
Study the possibilities of re-arrange the order of the layers per drag-and-drop in order to show only the Legend of the layer on the top of the list.

**Comment by acorbi** [comment]
In order to solve the problematic of displaying several explanatory texts at the same time (when several layers are active ), those texts could be presented in the layer selection list as depicted below:
![bildschirmfoto 2015-06-17 um 12 07 04](https://cloud.githubusercontent.com/assets/384894/8204505/669ddc26-14e9-11e5-8f9d-45dc4fb4f0ab.png)
However, texts can become quite long and therefore a maximal number of characters/words should be defined in order to limit the length of the content. Or even making the text collapsible/extensible...

**Comment by acorbi** [comment]
Fixed via fb8f5cbbe814ff09ed90b72f8065a3921a0f613f
