### ISSUE TITLE
The English texts not translate properly in Khmer site

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/opendev-wptheme#952]
Those English texts are translated if you look at the Po file in the language directory (Line: 2970 to 3036). However, the english texts still appear in Khmer site, https://cambodia.pp.opendevelopmentmekong.net/kh/profiles/economic-land-concessions/. 
https://github.com/OpenDevelopmentMekong/odm-frontend/blob/master/wp-content/languages/km.po

![screenshot_2](https://cloud.githubusercontent.com/assets/6613530/16328806/e9d0324e-3a07-11e6-9e94-32aef60c24f2.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/6613530/16328827/281279ea-3a08-11e6-8451-029a939db63a.png)

It is very strange to me that every thing view in my Localhost/DE is fine. See the screenshot below.

![screenshot_4](https://cloud.githubusercontent.com/assets/6613530/16328931/f9602cae-3a08-11e6-891c-7ae1623ef3d2.png)

**Comment by acorbi** [comment]
@Huyeng those translations on the .po file on https://github.com/OpenDevelopmentMekong/odm-frontend/blob/master/wp-content/languages/km.po#L2970 are commented out...

The important .po files are actually those present on the **i18n** folder of each of the repositories, see:

https://github.com/OpenDevelopmentMekong/opendev-wptheme/tree/master/i18n
https://github.com/OpenDevelopmentMekong/jeo/tree/master/i18n

And once deployed in production:

https://github.com/OpenDevelopmentMekong/wp-odm_tabular_pages/tree/master/i18n
https://github.com/OpenDevelopmentMekong/wp-odm_profile_pages/tree/master/i18n

In order to fix the Issue you raised, I have updated the khmer translation on transifex for **opendev-wptheme** (went from 33% to 36%) then downloaded the .po file into the i18n folder on the repository (https://github.com/OpenDevelopmentMekong/opendev-wptheme/commit/548b6d8e35e8626d10a5922c8160ee1a38fc7076) and pushed the changes so the translations are deployed by the **odm-automation** scripts.

Fixed via 548b6d8e35e8626d10a5922c8160ee1a38fc7076

**Comment by Huyeng** [comment]
Thanks for checking.
The file is not the last updated. I will push the latest one.
